# Generated by Django 5.1.4 on 2025-02-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_tracker', '0003_remove_userprofile_role_environmentalobservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalobservation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='environmentalobservation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='environmentalobservation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
