# Generated by Django 5.1.4 on 2025-02-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_tracker', '0004_remove_environmentalobservation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalobservation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentalobservation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
