# Generated by Django 5.1.4 on 2025-02-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_tracker', '0005_environmentalobservation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='environmentalobservation',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='environmentalobservation',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalobservation',
            name='photo',
            field=models.ImageField(upload_to='observations/'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='diet',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('omnivore', 'Omnivore'), ('pescatarian', 'Pescatarian')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='energy_usage',
            field=models.FloatField(help_text='Energy usage in kWh/day. Must be between 0 and 100.'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='transportation',
            field=models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('bike', 'Bike'), ('walk', 'Walk'), ('train', 'Train')], max_length=50),
        ),
    ]
