# Generated by Django 5.1.4 on 2025-02-27 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_tracker', '0006_create_fixed_shop_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('points_required', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='environmentalobservation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='environmentalobservation',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='environmentalobservation',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='environmentalobservation',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='environmentalobservation',
            name='photo',
            field=models.ImageField(upload_to='observations/'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='diet',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('omnivore', 'Omnivore'), ('pescatarian', 'Pescatarian')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='energy_usage',
            field=models.FloatField(help_text='Energy usage in kWh/day. Must be between 0 and 100.'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='transportation',
            field=models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('bike', 'Bike'), ('walk', 'Walk'), ('train', 'Train')], max_length=50),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_tracker.shopitem')),
            ],
        ),
    ]
