# Generated by Django 5.1.4 on 2025-02-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_tracker', '0007_shopitem_alter_environmentalobservation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalobservation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalobservation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='description',
            field=models.TextField(default='Description Not Provided'),
        ),
    ]
