# Generated by Django 5.1.5 on 2025-02-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_tracker', '0008_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(default='No description', upload_to='items/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='points_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
