# Generated by Django 5.1.4 on 2025-02-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_tracker', '0011_shopitem_image_url_alter_shopitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='distance_travelled',
            field=models.FloatField(default=0, help_text='Distance travelled in kms.'),
        ),
    ]
