# Generated by Django 5.1.4 on 2025-02-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_tracker', '0012_useractivity_distance_travelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='energy_usage',
            field=models.FloatField(default=0, help_text='Energy usage in kWh/day. Must be between 0 and 100.'),
        ),
    ]
